project:
  type: website
  output-dir: docs

website:
  title: "Abhishek Chakraborty"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: teaching.qmd
        text: teaching
      - href: research.qmd
        text: research
      - sidebar:projects
      - about.qmd

      
  sidebar:
    - id: projects
      title: "projects"
      contents:
        - sql_project.qmd
        - text_analysis_project.qmd
        - Rpackage.qmd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



